# Site Settings
title: 알고리줌
email: algorizum@zuminternet.com
description: 줌인터넷 알고리즘 스터디
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://algorizum.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: yevgnenll
user_description: 일단 만들어봤습니다
disqus_username: disqus_oIj0DdY0sx

# Social Media
# Remove the item if you don't need it
github_username: algorizum
# facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
